name: Build
# Avoid triggering two build on PR
# https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/2
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32

      - name: Install and Build 🔧
        run: |
          pnpm i
          MESSAGE=$(git log -1 HEAD --pretty=format:%s)
          if [[ "$MESSAGE" == *fgen* ]]; then
            pnpm generate
          else
            git diff --name-only HEAD~1 HEAD | grep src/data.ts && pnpm generate
          fi
          pnpm build:vite

      - name: Commit files
        run: |
          git config --local user.name github-actions[bot]
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git status
          git add .
          git diff-index --quiet HEAD || git commit -m "Generate README.md using src/data.ts"
          git log
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: false

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          git-config-name: 'github-actions[bot]'
          git-config-email: 'github-actions[bot]@users.noreply.github.com'
